// angular-app/src/app/app-view/app-view.component.ts
import { Component } from '@angular/core';
import angularLogo from '../../assets/angular.png';

@Component({
  selector: 'angular-app-view',
  templateUrl: './app-view.component.html',
  styleUrls: ['./app-view.component.scss'],
})
export class AppViewComponent {
  angularLogo = angularLogo;

  ngOnInit() {}
}

<a routerLink="foo">Foo</a>
<a routerLink="bar">Bar</a>

<img [src]="angularLogo" alt="Angular Logo" />

<router-outlet></router-outlet>

// react-app/src/appview/Main.tsx
import "./Main.css";
import reactLogo from "../../public/react.svg?inline";
import { Outlet, NavLink } from "react-router";

const Main = () => {
  return (
    <div className="react-app-view">
      <NavLink to="/foo">Foo</NavLink>
      <NavLink to="/bar">Bar</NavLink>
      <div>
        <img
          src={reactLogo}
          alt="React Logo"
          width={100}
          style={{ marginTop: 16 }}
        />
      </div>
      <Outlet />
    </div>
  );
};

export default Main;
